### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vlevit** [Phil-V/rgeocoder#2]
Hi,

Thank you for the library, it looks interesting!

This ticket is raising a license question.

README states

    Based on llambda/rust-reverse-geocoder and thampiman/reverse-geocoder.

It seems `thampiman/reverse-geocoder` is LGPL-licensed while `rgeocoder` is MIT-licensed. Now the question is whether `rgeocoder` can be considered as derivative of `thampiman/reverse-geocoder`? If it is the case I believe `rgeocoder` should be also copy-left licensed. If `rgeocoder` is not a derivative of `thampiman/reverse-geocoder` than perhaps it can be clarified in README?

Thanks,
Slava

**Comment by Phil-V** [comment]
Hi, thanks for the interest! This library is only loosely inspired by thampiman/reverse-geocoder (same general approach), but isn't based on any of its actual code. (The motivation was to replicate the same basic feature with a lower memory footprint, and slightly better performance when reverse-geocoding one location at a time instead of batches.). As such, it shouldn't qualify as a derivative.
I agree that the wording of the README is misleading and seems to imply otherwise, and I will fix it shortly.

**Comment by vlevit** [comment]
@Phil-V Thank you for the clarification!

**Comment by Phil-V** [comment]
Clarified relationship to other projects in 5611b23868372aef197b09230083b227d3aca2ae
